### YamlMime:ManagedReference
items:
- uid: IndustrialValley.Utility.Settings
  commentId: T:IndustrialValley.Utility.Settings
  id: Settings
  parent: IndustrialValley.Utility
  children: []
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: Settings
  fullName: IndustrialValley.Utility.Settings
  type: Class
  source:
    id: Settings
    path: F:\Unity Games\Industrial Valley\Industrial Valley\Assets\IndustrialValley\Scripts\Utility\Settings.cs
    startLine: 10
  assemblies:
  - IndustrialValley
  namespace: IndustrialValley.Utility
  syntax:
    content: public static class Settings
    content.vb: Public Module Settings
  inheritance:
  - System.Object
references:
- uid: IndustrialValley.Utility
  commentId: N:IndustrialValley.Utility
  href: IndustrialValley.html
  name: IndustrialValley.Utility
  nameWithType: IndustrialValley.Utility
  fullName: IndustrialValley.Utility
  spec.csharp:
  - uid: IndustrialValley
    name: IndustrialValley
    href: IndustrialValley.html
  - name: .
  - uid: IndustrialValley.Utility
    name: Utility
    href: IndustrialValley.Utility.html
  spec.vb:
  - uid: IndustrialValley
    name: IndustrialValley
    href: IndustrialValley.html
  - name: .
  - uid: IndustrialValley.Utility
    name: Utility
    href: IndustrialValley.Utility.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
memberLayout: SeparatePages
