### YamlMime:ManagedReference
items:
- uid: IndustrialValley.Game.SettingsData
  commentId: T:IndustrialValley.Game.SettingsData
  id: SettingsData
  parent: IndustrialValley.Game
  children:
  - IndustrialValley.Game.SettingsData.DropdownSettings
  - IndustrialValley.Game.SettingsData.SliderSettings
  - IndustrialValley.Game.SettingsData.ToggleSettings
  langs:
  - csharp
  - vb
  name: SettingsData
  nameWithType: SettingsData
  fullName: IndustrialValley.Game.SettingsData
  type: Class
  source:
    id: SettingsData
    path: F:\Unity Games\Industrial Valley\Industrial Valley\Assets\IndustrialValley\Scripts\Game\SaveSystem.cs
    startLine: 425
  assemblies:
  - IndustrialValley
  namespace: IndustrialValley.Game
  syntax:
    content: public class SettingsData
    content.vb: Public Class SettingsData
  inheritance:
  - System.Object
- uid: IndustrialValley.Game.SettingsData.SliderSettings
  commentId: P:IndustrialValley.Game.SettingsData.SliderSettings
  id: SliderSettings
  parent: IndustrialValley.Game.SettingsData
  langs:
  - csharp
  - vb
  name: SliderSettings
  nameWithType: SettingsData.SliderSettings
  fullName: IndustrialValley.Game.SettingsData.SliderSettings
  type: Property
  source:
    id: SliderSettings
    path: F:\Unity Games\Industrial Valley\Industrial Valley\Assets\IndustrialValley\Scripts\Game\SaveSystem.cs
    startLine: 428
  assemblies:
  - IndustrialValley
  namespace: IndustrialValley.Game
  syntax:
    content: public Dictionary<string, Dictionary<string, List<FloatSettingData>>> SliderSettings { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{IndustrialValley.Game.FloatSettingData}}}
    content.vb: Public Property SliderSettings As Dictionary(Of String, Dictionary(Of String, List(Of FloatSettingData)))
  overload: IndustrialValley.Game.SettingsData.SliderSettings*
- uid: IndustrialValley.Game.SettingsData.DropdownSettings
  commentId: P:IndustrialValley.Game.SettingsData.DropdownSettings
  id: DropdownSettings
  parent: IndustrialValley.Game.SettingsData
  langs:
  - csharp
  - vb
  name: DropdownSettings
  nameWithType: SettingsData.DropdownSettings
  fullName: IndustrialValley.Game.SettingsData.DropdownSettings
  type: Property
  source:
    id: DropdownSettings
    path: F:\Unity Games\Industrial Valley\Industrial Valley\Assets\IndustrialValley\Scripts\Game\SaveSystem.cs
    startLine: 429
  assemblies:
  - IndustrialValley
  namespace: IndustrialValley.Game
  syntax:
    content: public Dictionary<string, Dictionary<string, List<DropdownSettingData>>> DropdownSettings { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{IndustrialValley.Game.DropdownSettingData}}}
    content.vb: Public Property DropdownSettings As Dictionary(Of String, Dictionary(Of String, List(Of DropdownSettingData)))
  overload: IndustrialValley.Game.SettingsData.DropdownSettings*
- uid: IndustrialValley.Game.SettingsData.ToggleSettings
  commentId: P:IndustrialValley.Game.SettingsData.ToggleSettings
  id: ToggleSettings
  parent: IndustrialValley.Game.SettingsData
  langs:
  - csharp
  - vb
  name: ToggleSettings
  nameWithType: SettingsData.ToggleSettings
  fullName: IndustrialValley.Game.SettingsData.ToggleSettings
  type: Property
  source:
    id: ToggleSettings
    path: F:\Unity Games\Industrial Valley\Industrial Valley\Assets\IndustrialValley\Scripts\Game\SaveSystem.cs
    startLine: 430
  assemblies:
  - IndustrialValley
  namespace: IndustrialValley.Game
  syntax:
    content: public Dictionary<string, Dictionary<string, List<BoolSettingData>>> ToggleSettings { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{IndustrialValley.Game.BoolSettingData}}}
    content.vb: Public Property ToggleSettings As Dictionary(Of String, Dictionary(Of String, List(Of BoolSettingData)))
  overload: IndustrialValley.Game.SettingsData.ToggleSettings*
references:
- uid: IndustrialValley.Game
  commentId: N:IndustrialValley.Game
  href: IndustrialValley.html
  name: IndustrialValley.Game
  nameWithType: IndustrialValley.Game
  fullName: IndustrialValley.Game
  spec.csharp:
  - uid: IndustrialValley
    name: IndustrialValley
    href: IndustrialValley.html
  - name: .
  - uid: IndustrialValley.Game
    name: Game
    href: IndustrialValley.Game.html
  spec.vb:
  - uid: IndustrialValley
    name: IndustrialValley
    href: IndustrialValley.html
  - name: .
  - uid: IndustrialValley.Game
    name: Game
    href: IndustrialValley.Game.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: IndustrialValley.Game.SettingsData.SliderSettings*
  commentId: Overload:IndustrialValley.Game.SettingsData.SliderSettings
  href: IndustrialValley.Game.SettingsData.SliderSettings.html#IndustrialValley_Game_SettingsData_SliderSettings
  name: SliderSettings
  nameWithType: SettingsData.SliderSettings
  fullName: IndustrialValley.Game.SettingsData.SliderSettings
- uid: System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{IndustrialValley.Game.FloatSettingData}}}
  commentId: T:System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{IndustrialValley.Game.FloatSettingData}}}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<string, Dictionary<string, List<FloatSettingData>>>
  nameWithType: Dictionary<string, Dictionary<string, List<FloatSettingData>>>
  fullName: System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<IndustrialValley.Game.FloatSettingData>>>
  nameWithType.vb: Dictionary(Of String, Dictionary(Of String, List(Of FloatSettingData)))
  fullName.vb: System.Collections.Generic.Dictionary(Of String, System.Collections.Generic.Dictionary(Of String, System.Collections.Generic.List(Of IndustrialValley.Game.FloatSettingData)))
  name.vb: Dictionary(Of String, Dictionary(Of String, List(Of FloatSettingData)))
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: IndustrialValley.Game.FloatSettingData
    name: FloatSettingData
    href: IndustrialValley.Game.FloatSettingData.html
  - name: '>'
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: IndustrialValley.Game.FloatSettingData
    name: FloatSettingData
    href: IndustrialValley.Game.FloatSettingData.html
  - name: )
  - name: )
  - name: )
- uid: System.Collections.Generic.Dictionary`2
  commentId: T:System.Collections.Generic.Dictionary`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<TKey, TValue>
  nameWithType: Dictionary<TKey, TValue>
  fullName: System.Collections.Generic.Dictionary<TKey, TValue>
  nameWithType.vb: Dictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.Dictionary(Of TKey, TValue)
  name.vb: Dictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: IndustrialValley.Game.SettingsData.DropdownSettings*
  commentId: Overload:IndustrialValley.Game.SettingsData.DropdownSettings
  href: IndustrialValley.Game.SettingsData.DropdownSettings.html#IndustrialValley_Game_SettingsData_DropdownSettings
  name: DropdownSettings
  nameWithType: SettingsData.DropdownSettings
  fullName: IndustrialValley.Game.SettingsData.DropdownSettings
- uid: System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{IndustrialValley.Game.DropdownSettingData}}}
  commentId: T:System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{IndustrialValley.Game.DropdownSettingData}}}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<string, Dictionary<string, List<DropdownSettingData>>>
  nameWithType: Dictionary<string, Dictionary<string, List<DropdownSettingData>>>
  fullName: System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<IndustrialValley.Game.DropdownSettingData>>>
  nameWithType.vb: Dictionary(Of String, Dictionary(Of String, List(Of DropdownSettingData)))
  fullName.vb: System.Collections.Generic.Dictionary(Of String, System.Collections.Generic.Dictionary(Of String, System.Collections.Generic.List(Of IndustrialValley.Game.DropdownSettingData)))
  name.vb: Dictionary(Of String, Dictionary(Of String, List(Of DropdownSettingData)))
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: IndustrialValley.Game.DropdownSettingData
    name: DropdownSettingData
    href: IndustrialValley.Game.DropdownSettingData.html
  - name: '>'
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: IndustrialValley.Game.DropdownSettingData
    name: DropdownSettingData
    href: IndustrialValley.Game.DropdownSettingData.html
  - name: )
  - name: )
  - name: )
- uid: IndustrialValley.Game.SettingsData.ToggleSettings*
  commentId: Overload:IndustrialValley.Game.SettingsData.ToggleSettings
  href: IndustrialValley.Game.SettingsData.ToggleSettings.html#IndustrialValley_Game_SettingsData_ToggleSettings
  name: ToggleSettings
  nameWithType: SettingsData.ToggleSettings
  fullName: IndustrialValley.Game.SettingsData.ToggleSettings
- uid: System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{IndustrialValley.Game.BoolSettingData}}}
  commentId: T:System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{IndustrialValley.Game.BoolSettingData}}}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  name: Dictionary<string, Dictionary<string, List<BoolSettingData>>>
  nameWithType: Dictionary<string, Dictionary<string, List<BoolSettingData>>>
  fullName: System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<IndustrialValley.Game.BoolSettingData>>>
  nameWithType.vb: Dictionary(Of String, Dictionary(Of String, List(Of BoolSettingData)))
  fullName.vb: System.Collections.Generic.Dictionary(Of String, System.Collections.Generic.Dictionary(Of String, System.Collections.Generic.List(Of IndustrialValley.Game.BoolSettingData)))
  name.vb: Dictionary(Of String, Dictionary(Of String, List(Of BoolSettingData)))
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: IndustrialValley.Game.BoolSettingData
    name: BoolSettingData
    href: IndustrialValley.Game.BoolSettingData.html
  - name: '>'
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: IndustrialValley.Game.BoolSettingData
    name: BoolSettingData
    href: IndustrialValley.Game.BoolSettingData.html
  - name: )
  - name: )
  - name: )
memberLayout: SeparatePages
